### ISSUE TITLE
I need your urgent help

### ISSUE THREAD

**Issue by ShadowVicky** [dilithjay/IndexRL#2]
How can I train and test my own dataset for STR using parseq model.
I am facing problem .
If i will share my dataset,It is very samll data around 1500 assamese img data.Can you give me results along the code.
I am new in this field.

**Comment by dilithjay** [comment]
@ShadowVicky I think you may be on the wrong repo. Please take a look at [this](https://dilithjay.com/blog/parseq-train-a-custom-model/) guide and if it doesn't work, let me know through the [Contact Me](https://dilithjay.com/contact-me/) page or use the comment section. I'll help out.
